### ISSUE TITLE
RAW File transfer

### ISSUE THREAD

**Issue by henningdekode** [simonmitchell/rocc#25]
### Enable RAW file transfer
Ddoes the manufacturer source support RAW file transfer? I think that would make this library really stand out!

**Comment by simonmitchell** [comment]
Hiya, so yes but it depends on the model, and the mechanism used to initiate transfer!

Sony supports it on most models prior to the a7iii series (a7iii, a7riii, a9). You need to connect using the "Smart Remote Control" app rather than the "Send to Smartphone" menu option, and then use the info in README to enter transfer mode :)
